name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop


defaults:
 run:
  working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '21.x'

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build --if-present

    - name: Run unit tests
      run: npm run test

    - name: Create build tag
      id: tag
      run: |
        COMMIT_HASH=$(git rev-parse --short=7 $GITHUB_SHA)
        TAG="build-${COMMIT_HASH}"
        git tag $TAG
        git push origin $TAG
