name: Release Candidate Pipeline

on:
  push:
    tags:
      - 'rc-*'

defaults:
 run:
  working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm ci

    - name: Run static code analysis
      run: npm run lint

    - name: Run unit tests
      run: npm run test

    - name: Build the project
      run: npm run build --if-present

    - name: Remove node_modules folder
      run: rm -rf node_modules

    - name: Upload release package
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ${{ github.ref_name }}
        path: |
          ./
          !./.git/
